name: R-CI-Test

on: [push]

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore packages from renv.lock
        run: Rscript -e 'renv::restore(confirm = FALSE)'

      - name: Run R script(s)
        run: Rscript test.R
