name: R-CI-Test

on:
  push:
    branches: [main]

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    container: rocker/r-ver:4.4.0

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore packages from renv.lock
        run: Rscript -e 'renv::restore(confirm = FALSE)'

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
