jobs:
  run-r-script:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.4.0
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore packages from renv.lock
        run: Rscript -e 'renv::restore(confirm = FALSE)'

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
